### ISSUE TITLE
"Or" not recognized

### ISSUE THREAD

**Issue by jugdemon** [stefalie/cga-parser#2]
The or expression || is not recognized, as the split separator is tested before and gives a match of two split separators. I moved the or expression up in precedence by moving it before the split separator in the evaluation order in `t_symbol`

`        r"~|'|\.|:|\|\||\||,|\(|\)|{|}|\[|\]|-->|\*|\/|%|\+|\-|==|<=|>=|<|>|=|!=|!|&&"`

@stefalie could you verify this on Parthenon?  Previously line 46 caused the error. However, there is another parsing problem which is now visible. I'll track it down next.

**Comment by stefalie** [comment]
The Parthenon fails because of missing implementation on line 735. n_conditional_expr should look similar n_conditional (and there also already a prepared class called CaseExpr).

Similar to this for stochastic expressions, n_stochastic_expr should fill a ProbExpr (similar to n_stochastic which fills a StochasticRule object).

No time to do that right now, sorry.

**Comment by jugdemon** [comment]
Thanks for figuring it out.

I will skip out on the Parthenon for now. I need to fix up a few other things first, however, once I am done with that, I will try to get the exprs in.
