### ISSUE TITLE
split additional parameters not recognized

### ISSUE THREAD

**Issue by jugdemon** [stefalie/cga-parser#3]
A split apparently can have a list of parameters, as far as I understand the parameters do not get parsed properly and cause nodes not to be evaluated by spark.

Do you know which expression in `cga.py`to change in order for the parser to accept multiple parameters to splits?

I pushed a version to my branch that contains a more detailed error logger added to spark. You might want to use it to find the error.

**Comment by stefalie** [comment]
Oh, wasn't aware of that a split can have more than 1 param. Currently it takes only one param which is the split direction (line 317):
    def p_inst_3(self, args):
        ' inst ::= split_tok ( name ) sub_split '

**Comment by jugdemon** [comment]
I am not quite sure how to best extend it. Would it make sense to introduce a "nameList" that consists of at least one name?

I will use a different example for now, as I am not sure how to best extend this. When you have time, could you fix this?

**Comment by stefalie** [comment]
There already exists a parse pattern for "arg_list" (which is basically a name list). Replacing the "name" with "arg_list" should do the job. But then you might want that argument list to be a child of the AST node instead of it's "value".

Then we also have to adapt the Split class to hold more than one argument.

One sec, I'll have a look.

**Comment by stefalie** [comment]
Ok I fixed it. I only fixed it for 'split', I don't know if the component split can also take more than one argument.
